name: go_router_cola_annotation
description: A new Flutter package project.
version: 0.0.2
# homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.8.0
  go_router: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
